# Generated by Django 5.0.14 on 2026-07-07 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', '待完成'), ('completed', '已完成')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('avatar_text', models.CharField(blank=True, max_length=8)),
                ('avatar_url', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='literaturerecord',
            new_name='research_li_source_861c82_idx',
            old_name='research_li_source_7c7c0c_idx',
        ),
        migrations.RenameIndex(
            model_name='literaturerecord',
            new_name='research_li_publish_2e5454_idx',
            old_name='research_li_publish_65bf54_idx',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['owner', 'status'], name='research_to_owner_i_3a9f19_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['due_date'], name='research_to_due_dat_d273ef_idx'),
        ),
    ]
